// Extracts Strava's heatmap color ramps from the Strava maps engine data package
// and writes them to src/clients/common/palettes.js.
//
// Strava renders the global heatmap from grayscale tiles: the red channel of each
// tile pixel (0-255) indexes a 256x1 RGBA ramp texture shipped with the engine.
//
// Usage: node scripts/palettes.js [engineVersion]

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const ENGINE_VERSION = process.argv[2] || '34.0.0';
const BASE_URL = `https://wre-assets.prod.mapping.strava.com/releases/${ENGINE_VERSION}/assets/emscripten`;
const OUTPUT = path.join(process.cwd(), 'src/clients/common/palettes.js');

// palette name -> ramp texture in the engine package
const PALETTES = {
  blue: 'blue_dark',
  purple: 'purple_dark',
  orange: 'orange_dark',
  sunset: 'sunset_dark',
  pink: 'pink_dark',
  highcontrast: 'highcontrast_dark',
  bluered: 'bluered_dark',
};

async function download(file) {
  const response = await fetch(`${BASE_URL}/${file}`);
  if (!response.ok) throw new Error(`Failed to download ${file}: ${response.status}`);
  return Buffer.from(await response.arrayBuffer());
}

// Minimal decoder for the 8-bit, non-interlaced RGBA or indexed PNGs used by the ramps
function decodeRampPng(buffer) {
  let offset = 8;
  let width, bitDepth, colorType, interlace, palette, transparency;
  const idat = [];

  while (offset < buffer.length) {
    const length = buffer.readUInt32BE(offset);
    const type = buffer.toString('ascii', offset + 4, offset + 8);
    const data = buffer.subarray(offset + 8, offset + 8 + length);
    offset += 12 + length;

    if (type === 'IHDR') {
      width = data.readUInt32BE(0);
      bitDepth = data[8];
      colorType = data[9];
      interlace = data[12];
    } else if (type === 'PLTE') {
      palette = data;
    } else if (type === 'tRNS') {
      transparency = data;
    } else if (type === 'IDAT') {
      idat.push(data);
    }
  }

  if (bitDepth !== 8 || ![3, 6].includes(colorType) || interlace !== 0 || width !== 256) {
    throw new Error(
      `Unsupported ramp PNG (width=${width} depth=${bitDepth} color=${colorType} interlace=${interlace})`
    );
  }

  // Only the first row is needed (ramps are 256x1)
  const raw = zlib.inflateSync(Buffer.concat(idat));
  const bpp = colorType === 6 ? 4 : 1;
  const stride = width * bpp;
  const filter = raw[0];
  const row = Buffer.from(raw.subarray(1, 1 + stride));

  for (let i = 0; i < stride; i++) {
    const left = i >= bpp ? row[i - bpp] : 0;
    if (filter === 1 || filter === 4) {
      // Sub, or Paeth with an all-zero previous row
      row[i] = (row[i] + left) & 0xff;
    } else if (filter === 3) {
      row[i] = (row[i] + (left >> 1)) & 0xff;
    } else if (filter !== 0 && filter !== 2) {
      throw new Error(`Unsupported PNG filter ${filter}`);
    }
  }

  if (colorType === 6) return row;

  const rgba = Buffer.alloc(width * 4);
  for (let x = 0; x < width; x++) {
    const index = row[x];
    palette.copy(rgba, x * 4, index * 3, index * 3 + 3);
    rgba[x * 4 + 3] = transparency && index < transparency.length ? transparency[index] : 255;
  }
  return rgba;
}

async function main() {
  console.log(`Downloading Strava maps engine ${ENGINE_VERSION}...`);
  const [loader, data] = await Promise.all([
    download('SDLWasmLib.mjs'),
    download('SDLWasmLib.data'),
  ]);

  const files = {};
  for (const [, name, start, end] of loader
    .toString('utf-8')
    .matchAll(/filename:\s*"([^"]+)",\s*start:\s*(\d+),\s*end:\s*(\d+)/g)) {
    files[name] = data.subarray(Number(start), Number(end));
  }

  const lines = Object.entries(PALETTES).map(([name, texture]) => {
    const file = files[`/assets/Shared/Textures/Heatmap/${texture}.png`];
    if (!file) throw new Error(`Ramp texture not found: ${texture}`);
    return `  ${name}: '${decodeRampPng(file).toString('hex')}',`;
  });

  const output = [
    `// Generated by scripts/palettes.js from Strava maps engine ${ENGINE_VERSION}. Do not edit.`,
    '// Each palette is a 256-entry RGBA color ramp (hex encoded), indexed by the',
    '// intensity (red channel) of the grayscale heatmap tiles.',
    'export const PALETTES = {',
    ...lines,
    '};',
    '',
  ].join('\n');

  fs.writeFileSync(OUTPUT, output);
  console.log(`Wrote ${Object.keys(PALETTES).length} palettes to ${path.relative(process.cwd(), OUTPUT)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
